### ISSUE TITLE
Unwanted shouts being blocked

### ISSUE THREAD

**Issue by Shylo-Musgrove** [Chiaia/Windower-4-Addons#2]
I have the following items added to my list of things to be blocked:

- 'ML 0-20',
- 'ML  0-20',
- '0-20',
- '0~20/20',
- '0-20/20',

It blocks any shout/yell with "20" in it. The yell I missed was for a Kalunga V20 shout. I commented out the 5 strings above and was able to see the shout. The _**only**_ common thing in the shout and in my list of strings to block is 20. I searched (findall) everything else from the shout in my addon and there was no match.

I am running the current version of this addon.

**Comment by Chiaia** [comment]
\- is a magic character in lua pattern matching and needs to be escaped with & so 
&-

If you want to learn more about "Magical Characters" or Patterns in Lua: https://riptutorial.com/lua/example/20315/lua-pattern-matching

**Comment by Shylo-Musgrove** [comment]
Oh! I am familiar with escape characters I just had no idea the hyphen needed to be escaped. Thanks!
